name: Complete Devops Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t devopsmeet/devops:${{ env.SHORT_SHA }} .

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to DockerHub
        run: |
          docker push devopsmeet/devops:${{ env.SHORT_SHA }}
      - name: Configure Git Author
        run: |
          git config --local user.email "jaisikasaini@icloud.com"
          git config --local user.name "Manmeet2607"
      - name: Update Helm Chart with new Image tag
        run: |
          sed -i "s/tag:.*/tag ${{env.SHORT_SHA}}/" ./complete-devops-project-time-printer/values.yaml
          git add ./complete-devops-project-time-printer/values.yaml
          git commit -m "Updated image tag to ${{env.SHORT_SHA}}"
          git push
